### ISSUE TITLE
Failed to load the arduino-upload package

### ISSUE THREAD

**Issue by TECNEWSS** [Sorunome/arduino-upload#79]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [arduino-upload](https://github.com/Sorunome/arduino-upload) package 1.5.1

### Stack Trace

Failed to load the arduino-upload package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/arduino-upload/node_modules/space-pen/lib/space-pen.js:8:9)
    at /packages/arduino-upload/node_modules/space-pen/lib/space-pen.js:634:4)
    at /packages/arduino-upload/node_modules/space-pen/lib/space-pen.js:636:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/arduino-upload/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at /packages/arduino-upload/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at /packages/arduino-upload/node_modules/atom-space-pen-views/lib/main.js:24:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/arduino-upload/lib/output-view.coffee:1:10)
    at /packages/arduino-upload/lib/output-view.coffee:1:1)
    at /packages/arduino-upload/lib/output-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
```

### Commands

```
```

### Non-Core Packages

```
arduino-toolbelt 0.1.1 
arduino-upload 1.5.1 
atom-bean-builder 0.2.3 
autocomplete-clang 0.12.0 
build 0.70.0 
build-arduino 0.1.1 
busy-signal 2.0.1 
file-icons 2.1.35 
intentions 1.1.5 
language-arduino 0.4.3 
language-ini 1.22.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
tool-bar 1.1.12 
```

**Comment by IanM-Anderson** [comment]
I have the same bug as well, I tried downloading a previous version (not 1.8) as that one will just crash but now i get this error
